//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JummahManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Branches_Deleted
    {
        public string Branch_ID { get; set; }
        public string Branch_Name { get; set; }
        public string JIP_Name { get; set; }
        public string JIP_Contact { get; set; }
        public Nullable<int> No { get; set; }
        public string Street_Name { get; set; }
        public string City { get; set; }
        public string District { get; set; }
    }
}
