//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JummahManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Jummah_Schedule_temp
    {
        public int ID { get; set; }
        public int Row_Count { get; set; }
        public string Dhae_Name { get; set; }
        public string Dhae_Contact { get; set; }
        public string Branch_Name { get; set; }
        public string JIP_Name { get; set; }
        public string JIP_Contact { get; set; }
        public string Date { get; set; }
    }
}
