//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JummahManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbJummah_ManagementEntities : DbContext
    {
        public dbJummah_ManagementEntities()
            : base("name=dbJummah_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Branches> tbl_Branches { get; set; }
        public virtual DbSet<tbl_Branches_Deleted> tbl_Branches_Deleted { get; set; }
        public virtual DbSet<tbl_City> tbl_City { get; set; }
        public virtual DbSet<tbl_Dhae> tbl_Dhae { get; set; }
        public virtual DbSet<tbl_Dhae_Deleted> tbl_Dhae_Deleted { get; set; }
        public virtual DbSet<tbl_Jummah_Schedule> tbl_Jummah_Schedule { get; set; }
        public virtual DbSet<tbl_Jummah_Schedule_temp> tbl_Jummah_Schedule_temp { get; set; }
    }
}
